### PR TITLE
make lock.png loadable from anywhere

### PR DESCRIPTION
**Pull request by baptiste-dauphin**
Just call the script inside the fresh cloned repo :)

### CODE REVIEW

**Comment by petvas** [comment]
Hi, thank you for the PR What is troll.png is doing?

**Comment by baptiste-dauphin** [comment]
Another screen saver picture for my personal usage. My fault, I shouldn't have add this one :)
I can update the code if you want ? This var is not used...

**Comment by petvas** [comment]
Yes, please remove it and I will merge it.

**Comment by petvas** [comment]
The troll head clearly used...

**Pull request closed without merging**
